import { expect, test } from "@playwright/test";
import { seededData, users } from "../fixtures";
import { expectAuthenticatedShell, login, openApiSession, type ApiSession } from "../helpers";

/**
 * Gate F3 in the browser: an order moves stock inside a single transaction, an
 * inconsistent order leaves nothing behind, and cancellation is idempotent.
 */
test.describe("orders and stock", () => {
  async function fixtureProduct(session: ApiSession) {
    const response = await session.get<{
      data: Array<{ id: number; name: string; stock: number }>;
    }>("/api/v1/products?limit=100");
    const product = response.body.data.find((item) => item.name === seededData.alphaProductName);
    expect(product, "the fixture product must exist").toBeTruthy();
    return product!;
  }

  test("creating an order decrements stock exactly once and cancelling restores it", async ({
    browser,
  }) => {
    const manager = await openApiSession(browser, users.alphaManager.email);
    const before = await fixtureProduct(manager);

    const created = await manager.send<{ id: number; orderId: string }>("POST", "/api/v1/orders", {
      customer: "Pedido E2E",
      method: "PIX",
      status: "Pendente",
      lineItems: [{ productId: before.id, quantity: 3 }],
    });
    expect(created.status).toBe(201);
    // The public identifier is generated by the server, never by the client.
    expect(created.body.orderId).toMatch(/^ORD-/);

    expect((await fixtureProduct(manager)).stock).toBe(before.stock - 3);

    const cancel = await manager.send("DELETE", `/api/v1/orders/${created.body.id}`);
    expect(cancel.status).toBe(200);
    expect((await fixtureProduct(manager)).stock).toBe(before.stock);

    // Repeating the cancellation must not restore the stock twice.
    await manager.send("DELETE", `/api/v1/orders/${created.body.id}`);
    expect((await fixtureProduct(manager)).stock).toBe(before.stock);

    await manager.close();
  });

  test("an order that exceeds stock leaves no partial state", async ({ browser }) => {
    const manager = await openApiSession(browser, users.alphaManager.email);
    const before = await fixtureProduct(manager);

    const response = await manager.send<{ code?: string }>("POST", "/api/v1/orders", {
      customer: "Pedido impossivel",
      method: "PIX",
      status: "Pendente",
      lineItems: [{ productId: before.id, quantity: before.stock + 50 }],
    });
    expect(response.status).toBe(400);
    expect(response.body.code).toBe("INSUFFICIENT_STOCK");

    expect((await fixtureProduct(manager)).stock).toBe(before.stock);

    await manager.close();
  });

  test("order totals come from item snapshots, not from the client", async ({ browser }) => {
    const manager = await openApiSession(browser, users.alphaManager.email);
    const product = await fixtureProduct(manager);

    const created = await manager.send<{ id: number; total: number }>("POST", "/api/v1/orders", {
      customer: "Pedido com total forjado",
      method: "PIX",
      status: "Pendente",
      total: 0.01,
      lineItems: [{ productId: product.id, quantity: 2 }],
    });
    expect(created.status).toBe(201);

    // 2 x 49.90 must win over the value the client tried to impose.
    expect(created.body.total).toBeCloseTo(99.8, 2);

    const items = await manager.get<Array<{ quantity: number; unitPriceCents: number }>>(
      `/api/v1/orders/${created.body.id}/items`,
    );
    expect(items.status).toBe(200);
    expect(items.body).toHaveLength(1);
    expect(items.body[0].unitPriceCents).toBe(4990);

    await manager.send("DELETE", `/api/v1/orders/${created.body.id}`);
    await manager.close();
  });

  test("the orders screen lists an order created by the server", async ({ page }) => {
    await login(page, users.alphaManager.email);
    await expectAuthenticatedShell(page);

    await page.goto("/orders");
    await expect(page.getByText(/ORD-/).first()).toBeVisible({ timeout: 20_000 });
  });
});
